on:
  push:
    #tags:
    #  - "*"
name: "test"
jobs:
  test-local:
    if: false
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build + Test
        run: |
          mkdir -p dist/
          make loadable
          make test-loadable
  build-cross:
    name: Build cross-platform loadable files with Zig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - run: make cross-all
      - uses: actions/upload-artifact@v3
        with:
          name: path0-cross
          path: dist/cross
  test-dist-macos:
    name: Testing distribution macos
    runs-on: macos-latest
    needs: [build-cross]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: path0-cross
      - run: python3 tests/test-loadable.py dist/cross/x86_64-macos/path0.dylib
