on:
  push:
    tags:
      - "*"
name: "test"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build + Test
        run: |
          mkdir -p dist/
          make loadable
          make test-loadable
